// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MoodTubeOriginal.Data;
using System;

namespace MoodTubeOriginal.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20181028213542_Inittial")]
    partial class Inittial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoodTubeOriginal.Models.Mood", b =>
                {
                    b.Property<string>("MoodID")
                        .HasMaxLength(50);

                    b.HasKey("MoodID");

                    b.ToTable("Mood");
                });

            modelBuilder.Entity("MoodTubeOriginal.Models.Singer", b =>
                {
                    b.Property<string>("SingerID")
                        .HasMaxLength(50);

                    b.Property<string>("SingerName")
                        .HasMaxLength(50);

                    b.HasKey("SingerID");

                    b.ToTable("Singer");
                });

            modelBuilder.Entity("MoodTubeOriginal.Models.Song", b =>
                {
                    b.Property<string>("SongID")
                        .HasMaxLength(50);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MoodID")
                        .HasMaxLength(50);

                    b.Property<string>("SingerID")
                        .HasMaxLength(50);

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("SongID");

                    b.HasIndex("MoodID");

                    b.HasIndex("SingerID");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("MoodTubeOriginal.Models.Song", b =>
                {
                    b.HasOne("MoodTubeOriginal.Models.Mood", "Mood")
                        .WithMany("Songs")
                        .HasForeignKey("MoodID");

                    b.HasOne("MoodTubeOriginal.Models.Singer", "Singer")
                        .WithMany("Songs")
                        .HasForeignKey("SingerID");
                });
#pragma warning restore 612, 618
        }
    }
}
